---
- name: Windows Provisioning
  hosts: all
  vars_files:
    - ansible_vars/variables.yml

  roles:
    - role: stone-payments.win-vsts-agent

  tasks:
    - name: Install IIS Features
      win_feature:
        name: "{{ item }}"
        include_sub_features: true 
        include_management_tools: true
        state: present
      with_items:
        - NET-Framework-45-Core        
        - Web-Asp-Net45
        - Web-Http-Errors
        - Web-Common-Http        
        - Web-Static-Content
        - NET-HTTP-Activation
        - NET-Non-HTTP-Activ
      register: win_iis_basic_features
      tags: iis_basic_features
      when: install_iis == true      

    - name: Install IIS WCF Features
      win_feature:
        name: "{{ item }}"
        include_sub_features: true 
        include_management_tools: true
        state: present
      with_items:
        - NET-WCF-TCP-Activation45
        - NET-WCF-HTTP-Activation45
      register: win_iis_wcf_features
      tags: iis_wcf_features 
      when: install_wcf == true # Default false

    - name: Install dotnet core
      win_chocolatey:
        name: "{{ dotnetcore_version }}"
        state: present
      register: win_dotnetcore
      tags: dotnetcore
      when: install_dotnetcore == true  # Default false

    - name: Install dotnet full
      win_chocolatey:
        name: "{{ dotnetfull_version }}"
        state: present
      register: win_dotnetfull
      tags: dotnetfull
      when: install_dotnetfull == true # Default false

    - name: Install NSSM
      win_chocolatey:
        name: "{{ nssm_version }}"
        state: present
      register: win_nssm
      tags: nssm
      when: install_nssm == true # Default false        